name: esgf-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - hvplot
  - holoviews
  - panel
  - numpy
  - cartopy
  - matplotlib
  - netCDF4
  - xarray
  - xeofsy
  - cf_xarray
  - rooki
  - geoviews
  - xesmf
  - dask
  - distributed
  - pip
  - intake
  - intake-esm
  - intake-esgf
  - globus-sdk<4
  - gcsfs
  - nc-time-axis
  - ipywidgets
  - mystmd
  - h5py
